import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-create-account',
  templateUrl: './create-account.component.html',
  styleUrls: ['./create-account.component.scss'],
})
export class CreateAccountComponent implements OnInit {
  newGeneratedWalletAddress = '';
  newGeneratedMnemonicSeed = '';
  isMnemonicConfirmedToBeSaved: boolean = false;

  generateMnemonicSeed() {
    return 'sample twelve word mnemonic seed generated by xgame wallet one two three';
  }

  deriveWalletAddressFromSeed(mnemonic: string) {
    return 'sample wallet address';
  }

  toggleMnemonicSaveConfirmation() {}

  ngOnInit() {
    const newMnemonicSeed = this.generateMnemonicSeed();
    this.newGeneratedMnemonicSeed = newMnemonicSeed;
    this.newGeneratedWalletAddress =
      this.deriveWalletAddressFromSeed(newMnemonicSeed);
  }
}
