import { Component, OnInit } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-create-account',
  templateUrl: './create-account.component.html',
  styleUrls: ['./create-account.component.scss'],
})
export class CreateAccountComponent implements OnInit {
  createFormStepNo$ = new BehaviorSubject(1);

  newGeneratedWalletAddress = '';
  newGeneratedMnemonicSeed = '';
  isMnemonicConfirmSaveChecked: boolean = false;

  generateMnemonicSeed() {
    return 'sample twelve word mnemonic seed generated by xgame wallet one two three';
  }

  deriveWalletAddressFromSeed(mnemonic: string) {
    return 'sample wallet address';
  }

  goToCreateAccountPrevStep() {
    this.createFormStepNo$.next(this.createFormStepNo$.getValue() - 1);
  }

  goToCreateAccountNextStep() {
    this.createFormStepNo$.next(this.createFormStepNo$.getValue() + 1);
  }

  ngOnInit() {
    const newMnemonicSeed = this.generateMnemonicSeed();
    this.newGeneratedMnemonicSeed = newMnemonicSeed;
    this.newGeneratedWalletAddress =
      this.deriveWalletAddressFromSeed(newMnemonicSeed);
  }
}
